-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."completed_course" add column "course_completion_date" date
--  null;
